### ISSUE TITLE
Crear usuarios

### ISSUE THREAD

**Issue by ybenitezf** [soyedelangel/inventoria#4]
El administrador del sistema entra en el listado de usuario y selecciona la opción de agregar un nuevo usuario, depués rellena el formulario con lo datos del usuario (nombre, apellidos, sexo y correo electronico). Cuando se de guardar el nuevo usuario debe mostrarse en el listado de usuarios.

Para probarlo: volver al sistema, al listado de usuarios y verificar que el usuario recien creado aparezca en el listado. Alternativa: que el nuevo usuario pueda entrar en el sistema.

**Comment by soyedelangel** [comment]
Y si solo pongo. Hacer el CRUD para los usuarios?
Asumiendo que ya el programador esta familiarizado con eso

**Comment by soyedelangel** [comment]
Esto ya esta terminado
